### ISSUE TITLE
Problem with gd_get_biome ()

### ISSUE THREAD

**Issue by rosbakh** [valentinitnelav/plotbiomes#10]
Sorry, posted in a wrong branch!

**Comment by valentinitnelav** [comment]
Is this related to `plotbiomes` package? I don't seem to find `gd_get_biome()` function in our package.

**Comment by rosbakh** [comment]
Sorry, I mixed ggbiome and plotbiome packages up. I have reported the problem at the corresponding web-page, but it seems to me that the ggbiome is no longer maintained by the developer.

Is there an option in your package to find biome affinity for a list of sites with known coordinates/data on temperature and precipitation?

**Comment by valentinitnelav** [comment]
You can check our package [plotbiomes](https://github.com/valentinitnelav/plotbiomes).  I put some examples in the documentation [Whittaker biomes - examples](https://rawgit.com/valentinitnelav/plotbiomes/master/html/Whittaker_biomes_examples.html). Hope that helps you.
